apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dcs-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dcs-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: Helm
    managed-by: {{ .Values.labels.managedBy | quote }}
    owner: {{ .Values.labels.owner | quote }}
    dcs.ingress/enabled: {{ .Values.labels.dcsIngress.enabled | quote }}
    dcs.ingress/host: {{ default "" .Values.labels.dcsIngress.host | quote }}
    dcs.ingress/path: {{ default "/" .Values.labels.dcsIngress.path | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "dcs-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "dcs-app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        managed-by: {{ .Values.labels.managedBy | quote }}
        owner: {{ .Values.labels.owner | quote }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.image.pullSecrets | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      {{- end }}
      containers:
        - name: {{ include "dcs-app.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.containerSecurityContext }}
          securityContext: {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env: {{- toYaml .Values.env | nindent 12 }}
          {{- if .Values.envFrom }}
          envFrom: {{- toYaml .Values.envFrom | nindent 12 }}
          {{- end }}
          {{- if and .Values.config.enabled (gt (len .Values.config.data) 0) }}
          volumeMounts:
            - name: app-config
              mountPath: /app/config
          {{- end }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
      {{- if and .Values.config.enabled (gt (len .Values.config.data) 0) }}
      volumes:
        - name: app-config
          configMap:
            name: {{ include "dcs-app.fullname" . }}
      {{- end }}

